(function() {
    mpin.template = {};
    mpin.template['mobile-setup'] = ['<div class="pinpad" id="topNav">',
        '    <a id="mp_action_home" href="#">',
        '        <div id="homeBtn"></div>',
        '    </a>',
        '    <div id="mpinLogo"></div>',
        '</div>',
        '',
        '<div id="mpinMobileTitle">',
        '	<%=hlp.text( "mobileGet_header") %>',
        '</div>',
        '',
        '<div id="pinsHolder">',
        '	<div class="mpinMobileHolder" id="mpinSetupHolder">',
        '		<p>',
        '			<%=hlp.text( "mobileGet_text1") %>',
        '		</p>',
        '		',
        '		<span id="mpin_qrcode">',
        '		</span>',
        '		',
        '		<p>',
        '			<%=hlp.text( "mobileGet_text2") %>',
        '			<br />',
        '            <%= mobileAppFullURL %>',
        '		</p>',
        '		',
        '	</div>',
        '	',
        '	<div id="mpinMobileButton">',
        '		<button id="mp_action_cancel" class="mpinMobileButton">',
        '				<%=hlp.text( "mobileGet_button_back") %>',
        '		</button>',
        '	</div>',
        '</div>',
        '',
        '<div id="mpinFooter">',
        '    <div id="homeBtn"></div>',
        '</div>'].join('');

    mpin.template['accounts-panel'] = ['<div id="mp_accountListView" class="active">',
        '    <div class="mp_customScrollBox">',
        '        <div class="mp_container">',
        '            <div id="mp_accountContent" class="mp_content"></div>',
        '        </div>',
        '    </div>',
        '</div>',
        '',
        '<div id="bottomBtnHolder">',
        '	<button class="mpinBtn" id="mp_acclist_adduser">',
        '		<span class="btnLabel"><%=hlp.text("account_button_addnew") %></span>',
        '	</button>',
        '</div>'].join('');

    mpin.template['delete-warning'] = ['<!-- Home/Top Nav Bar -->',
        '',
        '<div id="topNav">',
        '    <div id="mp_action_home">',
        '    </div>',
        '    <div id="mpinLogo">',
        '    </div>',
        '</div>',
        '',
        '<!-- User section -->',
        '',
        '<div id="header">',
        '  <div id="menuIcon"></div>',
        '  <div id="mpinLogo"></div>',
        '</div>',
        '',
        '<!-- Input button -->',
        '',
        '<div id="identityContainer">',
        '',
        '  <div class="identityMainText">',
        '      <div class="congrats">',
        '        <%= hlp.text("deactivated_header") %>',
        '      </div>',
        '',
        '      <div class="identityBodyText">',
        '          <p>',
        '			  <span class="mp_accountField">',
        '				  <%=  userId %>',
        '			  </span>',
        '          </p>',
        '          <p>',
        '            <%= hlp.text("deactivated_text1") %>',
        '          </p>',
        '          <p>',
        '              <%= hlp.text("deactivated_text2") %>',
        '          </p>',
        '      </div>',
        '  </div>',
        '',
        '  <div id="buttonsContainer">',
        '      <div class="mpinBtn" id="mp_action_go">',
        '          <span class="iconArrow"></span>',
        '          <span class="btnLabel"><%= hlp.text("deactivated_button_register") %></span>',
        '      </div>',
        '  </div> ',
        '',
        '</div>',
        '',
        '<div id="mpinFooter">',
        '    <div id="homeBtn">',
        '    </div>',
        '</div>'].join('');

    mpin.template['home_mobile'] = ['<div id="buttonsContainer">',
        '    <div class="mpinBtn mpinGreenBtn" id="mpin_mobile">',
        '        <span class="btnLabel">',
        '			<span class="mpinBold"><%=hlp.text( "signin_btn_mobile1") %></span>',
        '			<%=hlp.text( "signin_btn_mobile2") %>',
        '		</span>',
        '    </div>',
        '</div>',
        '<div class="mpinCenterTxt">',
        '	<%=hlp.text( "home_txt_between_btns") %>',
        '</div>'].join('');

    mpin.template['user-settings'] = ['<div id="mp_accountListView" class="active">',
        '    <div class="mp_customScrollBox">',
        '        <div class="mp_container">',
        '            <div id="mp_accountContent" class="mp_content">',
        '			',
        '			',
        '			    <div class="mp_accountField" style="padding: 10px 5px 50px 5px;">',
        '					<%=name %>',
        '				</div>',
        '				<div style="padding:0px 10px">',
        '					<button id="mp_deluser" class="mpinBtn" style="padding: 5px;" tabindex=-1>',
        '						<%=hlp.text( "account_button_delete")%>',
        '					</button>',
        '					<br />',
        '					<button id="mp_reactivate" class="mpinBtn" style="padding: 5px;" tabindex=-1>',
        '						<%=hlp.text( "account_button_reactivate")%>',
        '					</button>',
        '				</div>',
        '			',
        '			',
        '			',
        '			</div>',
        '        </div>',
        '    </div>',
        '</div>',
        '',
        '	',
        '<div id="bottomBtnHolder">',
        '	<button class="mpinBtn" id="mp_acclist_cancel">',
        '		<span class="btnLabel"><%=hlp.text("account_button_backToList") %></span>',
        '	</button>',
        '</div>'].join('');

    mpin.template['blank'] = ['﻿<div class="mpinHeader">',
        '    <div class="mpinLogo mpPointer"></div>',
        '	<div class="mpinHome mpPointer"></div>',
        '</div>',
        '',
        '<div class="mpinIdentityRow">',
        '	<div class="mpinArrowDown mpPointer mpHide" id="show_identity"></div>',
        '	<div class="mpinIdentity mpLeft20">alice@your-domain.com</div>',
        '</div>',
        '',
        '',
        '<div class="mpinMain mpPaddTop10">',
        '	<div class="mpinLists">',
        '		<ul>',
        '			<li class="mpinRow">',
        '				<div class="mpinSettings"></div>',
        '				ONE ONE',
        '			</li>',
        '			<li class="mpinRow">',
        '				<div class="mpinSettings"></div>',
        '				Two Two',
        '			</li>',
        '			<li class="mpinRow">',
        '				<div class="mpinSettings"></div>',
        '				ONE ONE',
        '			</li>',
        '			<li class="mpinRow">',
        '				<div class="mpinSettings"></div>',
        '				ONE ONE',
        '			</li>',
        '			<li class="mpinRow">',
        '				<div class="mpinSettings"></div>',
        '				ONE ONE',
        '			</li>',
        '		</ul>',
        '	</div>',
        '	',
        '	<div class="mpinBtnBox">',
        '		<div class="mpinButton">',
        '			Add a new identity',
        '		</div>',
        '		',
        '		<div class="mpinButton mpGreen">',
        '			Sign in with your Smartphone',
        '		</div>',
        '	</div>',
        '	',
        '</div>',
        '',
        '',
        '<div class="mpinIdentityRow mpinFooterRow">',
        '	<div class="mpinArrowUp mpPointer"></div>',
        '</div>',
        '	',
        '<!--',
        '<div class="mpinMain mpinPinpad">',
        '',
        '	<div class="mpinInput">',
        '		<div class="mpinInputIn">',
        '			<div class="mpinCircle">',
        '				<div class="mpinCircleOut"></div>',
        '				<div class="mpinCircleIn"></div>',
        '			</div>',
        '			',
        '			<div class="mpinCircle">',
        '				<div class="mpinCircleOut"></div>',
        '				<div class="mpinCircleIn"></div>',
        '			</div>',
        '			<div class="mpinCircle">',
        '				<div class="mpinCircleOut"></div>',
        '				<div class="mpinCircleIn"></div>',
        '			</div>',
        '			<div class="mpinCircle">',
        '				<div class="mpinCircleOut"></div>',
        '				<div class="mpinCircleIn"></div>',
        '			</div>',
        '		</div>',
        '    </div>',
        '	',
        '	',
        '	<div class="mpin-pre-row">',
        '        <div class="mpin-row">',
        '            <button class="mpinPadBtn" data-value="1">',
        '                1',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="2">',
        '                2',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="3">',
        '                3',
        '            </button>',
        '        </div>',
        '    </div>',
        '    <div class="mpin-pre-row">',
        '        <div class="mpin-row">',
        '            <button class="mpinPadBtn" data-value="4">',
        '                4',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="5">',
        '                5',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="6">',
        '                6',
        '            </button>',
        '        </div>',
        '    </div>',
        '    <div class="mpin-pre-row">',
        '        <div class="mpin-row">',
        '            <button class="mpinPadBtn" data-value="7">',
        '                7',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="8">',
        '                8',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="9">',
        '                9',
        '            </button>',
        '        </div>',
        '    </div>',
        '    <div class="mpin-pre-row">',
        '        <div class="mpin-row mpin-bottom">',
        '            <button class="mpinPadBtn mpinPadBtnClear" data-value="clear" id="mpinClear">',
        '                clear',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="0">',
        '                0',
        '            </button>',
        '            <button class="mpinPadBtn mpinPadBtnLogin" data-value="go" id="mpinLogin">',
        '                login',
        '            </button>',
        '        </div>',
        '    </div>',
        '',
        '</div>',
        '-->	',
        '',
        '<div class="mpinFooter">',
        '	<div class="mpinPowered"></div>',
        '	<div class="mpinHelpHub mpPointer"></div>',
        '</div>'].join('');

    mpin.template['setup'] = ['<div class="pinpad" id="topNav">',
        '    <a id="mp_action_home" href="#">',
        '        <div id="homeBtn"></div>',
        '    </a>',
        '    <div id="mpinLogo"></div>',
        '</div>',
        '<div id="accountTopBar">',
        '    <div id="mpinUser">',
        '        <p><%= email %> <% console.log("cfg :::", cfg); %></p>',
        '    </div>',
        '</div>',
        ' ',
        '<div id="pinsHolder">',
        '',
        '    <div id="inputContainer">',
        '        <input id="pinpad-input" type="text" readonly="true" placeholder="<%= hlp.text("pinpad_placeholder_text") %>">',
        '    </div>',
        '',
        '    <div class="pre-row">',
        '        <div class="row">',
        '            <button class="btn" data-value="1">',
        '                1',
        '            </button>',
        '            <button class="btn" data-value="2">',
        '                2',
        '            </button>',
        '            <button class="btn" data-value="3">',
        '                3',
        '            </button>',
        '        </div>',
        '    </div>',
        '    <div class="pre-row">',
        '        <div class="row">',
        '            <button class="btn" data-value="4">',
        '                4',
        '            </button>',
        '            <button class="btn" data-value="5">',
        '                5',
        '            </button>',
        '            <button class="btn" data-value="6">',
        '                6',
        '            </button>',
        '        </div>',
        '    </div>',
        '    <div class="pre-row">',
        '        <div class="row">',
        '            <button class="btn" data-value="7">',
        '                7',
        '            </button>',
        '            <button class="btn" data-value="8">',
        '                8',
        '            </button>',
        '            <button class="btn" data-value="9">',
        '                9',
        '            </button>',
        '        </div> ',
        '    </div>',
        '    <div class="pre-row">',
        '        <div class="row bottom">',
        '            <button class="btnClear" data-value="clear" id="mpinClear" disabled>',
        '                <span class="label"><%= hlp.text("setupPin_button_clear") %></span>',
        '            </button>',
        '            <button class="btn" data-value="0">',
        '                <span class="label mp_pindigit">0</span>',
        '            </button>',
        '            <button class="btnLogin" data-value="go" id="mpinLogin" disabled>',
        '                <span class="label"><%= hlp.text("setupPin_button_done") %></span>',
        '            </button>',
        '        </div>',
        '    </div>',
        '</div>',
        '<div class="pinpad" id="mpinFooter">',
        '    <div id="homeBtn"></div>',
        '</div>'].join('');

    mpin.template['delete-panel'] = ['<div id="mp_operationView" class="active">',
        '	<div class="mp_container">',
        '            ',
        '		<div class="mp_headerFrame">',
        '			<div class="mp_alertTitle">',
        '				<%=hlp.text( "account_delete_question") %>',
        '			</div>',
        '			<div class="mp_accountField">',
        '				<%=name %>',
        '			</div>',
        '		</div>',
        '		<div class="mp_bottomFrame">',
        '			<div style="padding:0px 10px">',
        '				<button id="mp_acclist_deluser" class="mpinBtn" tabindex=-1>',
        '					<%=hlp.text( "account_delete_button") %>',
        '				</button>',
        '			</div>',
        '			<button id="mp_acclist_cancel" class="mpinGreyButton" tabindex=-1>',
        '				<%=hlp.text( "account_button_cancel") %>',
        '			</button>',
        '		</div>',
        '	',
        '	</div>',
        '</div>',
        ''].join('');

    mpin.template['setup-done'] = ['<!-- Home/Top Nav Bar -->',
        '',
        '<div id="topNav">',
        '    <div id="mp_action_home">',
        '    </div>',
        '    <div id="mpinLogo">',
        '    </div>',
        '</div>',
        '',
        '<!-- User section -->',
        '',
        '<div id="header">',
        '  <div id="menuIcon"></div>',
        '  <div id="mpinLogo"></div>',
        '</div>',
        '',
        '<!-- Input button -->',
        '',
        '<div id="identityContainer">',
        '',
        '  <div class="identityMainText">',
        '      <div class="congrats">',
        '        <%= hlp.text("setupDone_header") %>',
        '      </div>',
        '',
        '      <div class="identityBodyText">',
        '          <p>',
        '              <%= hlp.text("setupDone_text1") %>',
        '                  <span class="mp_accountField">',
        '                      <%=  userId %>',
        '                  </span>',
        '          </p>',
        '          <p>',
        '            <%= hlp.text("setupDone_text2") %>',
        '          </p>',
        '          <p>',
        '              <%= hlp.text("setupDone_text3") %>',
        '          </p>',
        '      </div>',
        '  </div>',
        '',
        '  <div id="buttonsContainer">',
        '      <div class="mpinBtn" id="mp_action_go">',
        '          <span class="iconArrow"></span>',
        '          <span class="btnLabel"><%= hlp.text("setupDone_button_go") %></span>',
        '      </div>',
        '  </div> ',
        '',
        '</div>',
        '',
        '<div id="mpinFooter">',
        '    <div id="homeBtn">',
        '    </div>',
        '</div>'].join('');

    mpin.template['help-hub-3'] = ['﻿<div id="header">',
        '    <div id="mpinLogo"></div>',
        '</div>',
        '',
        '<info class="mpinHelpInfo helpHubTitle">',
        '	<%= hlp.text( "help_hub_li1") %>',
        '</info>',
        '',
        '<div class="mpinHelpBlock">',
        '	',
        '	<p><%= hlp.text( "help_hub_3_p1") %></p>',
        '	<p><%= hlp.text( "help_hub_3_p2") %></p>',
        '</div>',
        '',
        '<div class="mpinHelpHubFooter">',
        '	<div class="mpinBtn mpinBlueBtn" id="mpin_help_hub">',
        '		<span class="btnLabel">',
        '			<%=hlp.text( "help_hub_return_button") %>',
        '		</span>',
        '	</div>',
        '</div>',
        '',
        '<div id="mpinFooter">',
        '    <div id="homeBtn"></div>',
        '</div>'].join('');

    mpin.template['help-hub'] = ['<div id="header">',
        '    <div id="mpinLogo"></div>',
        '</div>',
        '',
        '<info class="mpinHelpInfo helpHubTitle">',
        '	<i></i>',
        '	<%= hlp.text( "help_hub_title") %>',
        '</info>',
        '',
        '<div class="mpinHelpBlock">',
        '	<ul>',
        '		<li id="mpin_hub_li1"><%= hlp.text( "help_hub_li1") %></li>',
        '		<li id="mpin_hub_li2"><%= hlp.text( "help_hub_li2") %></li>',
        '		<li id="mpin_hub_li3"><%= hlp.text( "help_hub_li3") %></li>',
        '		<li id="mpin_hub_li4"><%= hlp.text( "help_hub_li4") %></li>',
        '		',
        '	</ul>',
        '</div>',
        '<div class="mpinHelpHubFooter">',
        '	<div class="mpinBtn mpinBlueBtn" id="mpin_close_hub">',
        '		<span class="btnLabel">',
        '			<%=hlp.text( "help_hub_button") %>',
        '		</span>',
        '	</div>',
        '</div>',
        '',
        '<div id="mpinFooter">',
        '    <a href="#" class="mpinHelpHub"></a>',
        '	<div id="homeBtn"></div>',
        '</div>'].join('');

    mpin.template['reactivate-panel'] = ['<div id="mp_operationView" class="active">',
        '	<div class="mp_container">',
        '            ',
        '		<div class="mp_headerFrame">',
        '			<div class="mp_alertTitle">',
        '				<%=hlp.text( "account_reactivate_question") %>',
        '			</div>',
        '			<div class="mp_accountField">',
        '				<%=name %>',
        '			</div>',
        '		</div>',
        '		<div class="mp_bottomFrame">',
        '			<div style="padding:0px 10px">',
        '				<button id="mp_acclist_reactivateuser" class="mpinBtn" tabindex=-1>',
        '					<%=hlp.text( "account_reactivate_button") %>',
        '				</button>',
        '			</div>',
        '			<button id="mp_acclist_cancel" class="mpinGreyButton" tabindex=-1>',
        '				<%=hlp.text( "account_button_cancel") %>',
        '			</button>',
        '		</div>',
        '	',
        '	</div>',
        '</div>'].join('');

    mpin.template['home'] = ['<div id="header">',
        '    <div id="mpinLogo"></div>',
        '</div>',
        '  ',
        '<div class="mpinIntroText">',
        '	<%=hlp.text("home_intro_text") %>',
        '</div>',
        '',
        '<div id="renderMobileHome"></div>',
        '',
        '<div id="buttonsContainer">',
        '    <div class="mpinBtn mpinBlueBtn" id="mpin_desktop">',
        '        <span class="btnLabel">',
        '			<span class="mpinBold">',
        '				<%=hlp.text( "signin_btn_desktop1") %>',
        '			</span>',
        '			<%=hlp.text( "signin_btn_desktop2") %>',
        '		</span>',
        '    </div>',
        '',
        '	<info class="mpinHelpInfo" id="mpin_help">',
        '		<i></i>',
        '		<%= hlp.text( "home_hlp_link") %>',
        '	</info>',
        '</div>',
        '',
        '<div id="mpinFooter">',
        '	<a href="#" class="mpinHelpHub" id="mpin_desktop_hub"></a>',
        '    <div id="homeBtn"></div>',
        '</div>'].join('');

    mpin.template['help-hub-1'] = ['﻿<div id="header">',
        '    <div id="mpinLogo"></div>',
        '</div>',
        '',
        '<info class="mpinHelpInfo helpHubTitle">',
        '	<%= hlp.text( "help_hub_li1") %>',
        '</info>',
        '',
        '<div class="mpinHelpBlock">',
        '	<p><%= hlp.text( "help_hub_3_p1") %></p>',
        '	<p><%= hlp.text( "help_hub_3_p2") %></p>',
        '</div>',
        '',
        '<div class="mpinHelpHubFooter">',
        '	<div class="mpinBtn mpinBlueBtn" id="mpin_help_hub">',
        '		<span class="btnLabel">',
        '			<%= hlp.text( "help_hub_return_button") %>',
        '		</span>',
        '	</div>',
        '</div>',
        '',
        '<div id="mpinFooter">',
        '	<a href="#" class="mpinHelpHub"></a>',
        '    <div id="homeBtn"></div>',
        '</div>',
        '',
        ''].join('');

    mpin.template['identity-not-active'] = ['<!-- Home/Top Nav Bar -->',
        '<div class="pinpad" id="topNav">',
        '    <a id="mp_action_home" href="#">',
        '        <div id="homeBtn"></div>',
        '    </a>',
        '    <div id="mpinLogo"></div>',
        '</div>',
        '',
        '<!-- Input button -->',
        '',
        '<div id="identityContainer">',
        '',
        '  <div class="identityMainText">',
        '      <div>',
        '	  <h1><%= hlp.text("setupNotReady_header") %></h1>',
        '      </div>',
        '',
        '      <div class="mp_note" style="margin:0px; padding:0px">',
        '          <p class="mp_center">',
        '              <%=hlp.text( "setupNotReady_text1") %>',
        '                  <br/>',
        '                  <span style="padding: 10px 5px 20px 5px" class="mp_accountField">',
        '                      <%= email %>',
        '                  </span>',
        '                  <br/>',
        '                  <%=hlp.text( "setupNotReady_text2") %>',
        '          </p>',
        '          <p class="mp_after_center">',
        '              <%=hlp.text( "setupNotReady_text3") %>',
        '          </p>',
        '      </div>',
        '  </div>',
        '',
        '  <div id="buttonsContainer">',
        '      <div class="mpinBtn" id="mpin_setup">',
        '          <span class="iconArrow"></span>',
        '          <span class="btnLabel btnLabelArrow"><%=hlp.text( "setupNotReady_button_check") %></span>',
        '      </div>',
        '      <div class="mpinBtn" id="mpin_resend">',
        '          <span class="iconArrow"></span>',
        '          <span class="btnLabel btnLabelArrow"><%=hlp.text( "setupNotReady_button_resend")%></span>',
        '      </div>',
        '	  <div class="mpinBtn" id="mpin_accounts">',
        '          <span class="iconArrow"></span>',
        '          <span class="btnLabel btnLabelArrow"><%=hlp.text( "setupNotReady_button_back")%></span>',
        '      </div>',
        '  </div>',
        '',
        '</div>',
        '',
        '<div id="mpinFooter">',
        '    <div id="homeBtn">',
        '    </div>',
        '</div>'].join('');

    mpin.template['login'] = ['<div class="pinpad" id="topNav">',
        '    <a id="mp_action_home" href="#">',
        '        <div id="homeBtn"></div>',
        '    </a>',
        '    <div id="mpinLogo"></div>',
        '</div>',
        '',
        '<div id="accountTopBar">',
        '    <div id="mpinUser">',
        '    </div>',
        '		<div id="menuBtn"></div>',
        '</div>',
        ' ',
        '<div id="pinsHolder">',
        '',
        '    <div id="inputContainer">',
        '        <input id="pinpad-input" type="text" readonly="true" placeholder="<%= hlp.text("pinpad_placeholder_text") %>">',
        '    </div>',
        '',
        '    <div class="pre-row">',
        '        <div class="row">',
        '            <button class="btn" data-value="1">',
        '                1',
        '            </button>',
        '            <button class="btn" data-value="2">',
        '                2',
        '            </button>',
        '            <button class="btn" data-value="3">',
        '                3',
        '            </button>',
        '        </div>',
        '    </div>',
        '    <div class="pre-row">',
        '        <div class="row">',
        '            <button class="btn" data-value="4">',
        '                4',
        '            </button>',
        '            <button class="btn" data-value="5">',
        '                5',
        '            </button>',
        '            <button class="btn" data-value="6">',
        '                6',
        '            </button>',
        '        </div>',
        '    </div>',
        '    <div class="pre-row">',
        '        <div class="row">',
        '            <button class="btn" data-value="7">',
        '                7',
        '            </button>',
        '            <button class="btn" data-value="8">',
        '                8',
        '            </button>',
        '            <button class="btn" data-value="9">',
        '                9',
        '            </button>',
        '        </div>',
        '    </div>',
        '    <div class="pre-row">',
        '        <div class="row bottom">',
        '            <button class="btnClear" data-value="clear" id="mpinClear" disabled>',
        '                <span class="label">clear</span>',
        '            </button>',
        '            <button class="btn" data-value="0">',
        '                <span class="label mp_pindigit">0</span>',
        '            </button>',
        '            <button class="btnLogin" data-value="go" id="mpinLogin" disabled>',
        '                <span class="label">login</span>',
        '            </button>',
        '        </div>',
        '    </div>',
        '</div>',
        '<div id="mpinIdentities" style="display: none;">',
        '</div>',
        '',
        '',
        '',
        '<div class="pinpad" id="mpinFooter">',
        '    <div id="homeBtn"></div>',
        '</div>'].join('');

    mpin.template['setup-home'] = ['<!-- Home/Top Nav Bar -->',
        '',
        '<div id="topNav">',
        '    <div id="mp_action_home">',
        '    </div>',
        '    <div id="mpinLogo">',
        '    </div>',
        '</div>',
        '',
        '<!-- User section -->',
        '',
        '<div id="addIdentity">',
        '  <div class="identityHeader"><%=hlp.text( "setup_header") %></div>',
        '</div>',
        '',
        '<!-- Input button -->',
        '',
        '<div id="identityContainer" class="active">',
        '  <div class="inputContainer">',
        '    ',
        '    <div class="identityElHolder">',
        '      <div class="identityText">',
        '          <span><%=hlp.text( "setup_text1") %></span>',
        '      </div>',
        '',
        '      <div class="identityInput">',
        '        <div>',
        '          <input type="email" id="emailInput" placeholder="" value="<%= userId %>">',
        '        </div>',
        '      </div>',
        '    </div>',
        '',
        '  </div>',
        '',
        '  <div class="identityMainText">',
        '      <div>',
        '        <%=hlp.text( "setup_text2") %>',
        '      </div>',
        '  </div>',
        '',
        '</div>',
        '',
        '<div id="bottomBtnHolder">',
        '    <button class="mpinBtn" id="mp_action_setup">',
        '        <span class="btnLabel"><%=hlp.text( "setup_button_setup") %></span>',
        '    </button>',
        '</div>',
        '',
        '<div id="mpinFooter">',
        '    <div id="homeBtn">',
        '    </div>',
        '</div>'].join('');

    mpin.template['user-row'] = ['<div id="mp_StarIcon_<%= iNumber %>" class="mp_starIcon" tabindex=-1></div>',
        '<div class="mp_titleItem" title="<%= name %>">',
        '    <%=name %>',
        '</div>',
        '<div id="mp_btIdSettings_<%= iNumber %>" class="mp_buttonItem">',
        '    <img src="<%= hlp.img("id-settings.svg") %>" tabindex=-1/>',
        '</div>'].join('');

    mpin.template['help-hub-4'] = ['﻿<div id="header">',
        '    <div id="mpinLogo"></div>',
        '</div>',
        '',
        '<info class="mpinHelpInfo helpHubTitle">',
        '	<%= hlp.text( "help_hub_li1") %>',
        '</info>',
        '',
        '<div class="mpinHelpBlock">',
        '	',
        '	<p><%= hlp.text( "help_hub_3_p1") %></p>',
        '	<p><%= hlp.text( "help_hub_3_p2") %></p>',
        '</div>',
        '',
        '<div class="mpinHelpHubFooter">',
        '	<div class="mpinBtn mpinBlueBtn" id="mpin_help_hub">',
        '		<span class="btnLabel">',
        '			<%=hlp.text( "help_hub_return_button") %>',
        '		</span>',
        '	</div>',
        '</div>',
        '',
        '<div id="mpinFooter">',
        '    <div id="homeBtn"></div>',
        '</div>'].join('');

    mpin.template['help-tooltip'] = ['﻿<help id="mpinHelpTag">',
        '	<div id="mpinHelpContainer">',
        '	</div>',
        '</help>'].join('');

    mpin.template['help-hub-2'] = ['﻿<div id="header">',
        '    <div id="mpinLogo"></div>',
        '</div>',
        '',
        '<info class="mpinHelpInfo helpHubTitle">',
        '	<%= hlp.text( "help_hub_li1") %>',
        '</info>',
        '',
        '<div class="mpinHelpBlock">',
        '	',
        '	<p><%= hlp.text( "help_hub_3_p1") %></p>',
        '	<p><%= hlp.text( "help_hub_3_p2") %></p>',
        '</div>',
        '',
        '<div class="mpinHelpHubFooter">',
        '	<div class="mpinBtn mpinBlueBtn" id="mpin_help_hub">',
        '		<span class="btnLabel">',
        '			<%=hlp.text( "help_hub_return_button") %>',
        '		</span>',
        '	</div>',
        '</div>',
        '',
        '<div id="mpinFooter">',
        '    <div id="homeBtn"></div>',
        '</div>'].join('');

    mpin.template['help-tooltip-home'] = ['<p class="mpinHelpText">',
        '	<%=hlp.text( "help_text_1") %>',
        '</p>',
        '',
        '<div id="buttonsContainer">',
        '    <div class="mpinBtn mpinGreen mpinBtm10" id="mpin_help_ok">',
        '        <span class="btnLabel"><%=hlp.text( "help_ok_btn") %></span>',
        '    </div>',
        '    <div class="mpinBtn mpinGrey mpinBtm10" id="mpin_help_more">',
        '        <span class="btnLabel"><%=hlp.text( "help_more_btn") %></span>',
        '    </div>',
        '</div>'].join('');

    mpin.template['activate-identity'] = ['<!-- User section -->',
        '<div class="pinpad" id="topNav">',
        '    <a id="mp_action_home" href="#">',
        '        <div id="homeBtn"></div>',
        '    </a>',
        '    <div id="mpinLogo"></div>',
        '</div>',
        '',
        '<!-- Input button -->',
        '',
        '<div id="identityContainer">',
        '',
        '  <div class="identityMainText">',
        '		',
        '	<div>',
        '		<h1><%= hlp.text("setupReady_header") %></h1>',
        '    </div>',
        '	  ',
        '	    <div class="mp_note" style="margin:0px; padding:0px">',
        '          <p class="mp_center">',
        '              <%=hlp.text( "setupReady_text1") %>',
        '                  <br/>',
        '                  <span style="padding: 10px 5px 20px 5px" class="mp_accountField">',
        '                      <%= email %>',
        '                  </span>',
        '                  <br/>',
        '                  <%=hlp.text( "setupReady_text2") %>',
        '          </p>',
        '          <p class="mp_after_center">',
        '              <%=hlp.text( "setupReady_text3") %>',
        '          </p>',
        '      </div>',
        '  </div>',
        '',
        '  <div id="buttonsContainer">',
        '      <div class="mpinBtn" id="mpin_action_setup">',
        '          <span class="iconArrow"></span>',
        '          <span class="btnLabel btnLabelArrow"><%=hlp.text( "setupReady_button_go") %></span>',
        '      </div>',
        '      <div class="mpinBtn" id="mpin_action_resend">',
        '          <span class="iconArrow"></span>',
        '          <span class="btnLabel btnLabelArrow"><%=hlp.text( "setupReady_button_resend")%></span>',
        '      </div>',
        '  </div> ',
        '',
        '</div>',
        '',
        '<div id="mpinFooter">',
        '    <div id="homeBtn">',
        '    </div>',
        '</div>'].join('');

    mpin.template['mobile-login'] = ['<!-- Home/Top Nav Bar -->',
        '<div id="header">',
        '    <div id="mpinLogo"></div>',
        '</div> ',
        '',
        '<div class="mpinTabMiddle clrGreen mpinBtm10">',
        '	<div>',
        '		<%=hlp.text("mobile_header_txt1") %>',
        '		<span class="mpinColorRed"><%= hlp.text("mobile_header_donot") %></span>',
        '		<%=hlp.text("mobile_header_txt3") %>',
        '	</div>',
        '	<div>',
        '		<div id="homeIcon">',
        '			<div id="mobileIcon"></div>',
        '		</div>',
        '	</div>',
        '</div>',
        '',
        '<div class="mpinMobileGrBtn mpinBtm10">',
        '	<div class="mpinGrTxt" id="mpinDownWhite">',
        '		Sign in with Smartphone',
        '	</div>',
        '	<div class="mpinGrTxt">',
        '		Your Access Number is:',
        '		',
        '		<span id="mpinAccessNumber">',
        '		</span>',
        '',
        '	</div>',
        '	',
        '	<div class="mpinMobileWhBtn" id="mpin_seconds">',
        '		99 seconds',
        '	</div>',
        '</div>',
        '',
        '<div class="mpinBtn mpinBtm10" id="mpin_action_setup">',
        '    <span class="iconArrow"></span>',
        '    <span class="btnLabel btnLabelArrow"><%=hlp.text( "home_button_getMobile") %></span>',
        '</div>',
        '',
        '<div class="mpinMobileGrBtn mpinBtm10" id="mpin_login_desktop">',
        '    I <span class="mpinColorRed">DO</span> trust this computer',
        '</div>',
        '',
        '',
        '<div id="mpinFooter">',
        '	<a href="#" class="mpinHelpHub" id="mpin_desktop_hub"></a>',
        '    <div id="homeBtn">',
        '    </div>',
        '</div>'].join('');

    mpin.template['logout'] = ['<!-- Home/Top Nav Bar -->',
        '',
        '<div id="topNav">',
        '    <div id="mp_action_home">',
        '    </div>',
        '    <div id="mpinLogo">',
        '    </div>',
        '</div>',
        '',
        '<!-- User section -->',
        '',
        '<div id="header">',
        '  <div id="menuIcon"></div>',
        '  <div id="mpinLogo"></div>',
        '</div>',
        '',
        '<!-- Input button -->',
        '',
        '<div id="identityContainer">',
        '',
        '  <div class="identityMainText">',
        '      <div class="congrats">',
        '        <%= hlp.text("logout_text1") %>',
        '      </div>',
        ' ',
        '  </div>',
        '',
        '  <div id="buttonsContainer">',
        '      <div class="mpinBtn" id="mpin_action_logout">',
        '          <span class="iconArrow"></span>',
        '          <span class="btnLabel"><%= hlp.text("logout_button") %></span>',
        '      </div>',
        '  </div> ',
        '',
        '</div>',
        '',
        '<div id="mpinFooter">',
        '    <div id="homeBtn">',
        '    </div>',
        '</div>'].join('');

    mpin.template['desktop'] = ['﻿<!-- Home/Top Nav Bar -->',
        '<div id="header">',
        '    <div id="mpinLogo"></div>',
        '</div> ',
        '',
        '<div class="mpinTabMiddle clrBlue mpinBtm10">',
        '	<div>',
        '		<%=hlp.text("mobile_header_txt1") %>',
        '		<span class="mpinColorRed"><%= hlp.text("mobile_header_do") %></span>',
        '		<%=hlp.text("mobile_header_txt3") %>',
        '	</div>',
        '	<div>',
        '		<div id="homeIcon">',
        '			<div id="desktopIcon"></div>',
        '		</div>',
        '	</div>',
        '</div>',
        '',
        '<div id="buttonsContainer">',
        '	<div class="mpinBtn mpinBtm10">',
        '		<span class="iconArrow"></span>',
        '		<span class="btnLabel btnLabelArrow"><%=hlp.text( "signin_btn_desktop1") %></span>',
        '	</div>',
        '',
        '	<div class="mpinBtn mpinBtm10">',
        '		<span class="iconArrow"></span>',
        '		<span class="btnLabel btnLabelArrow"><%=hlp.text( "signin_btn_desktop2") %></span>',
        '	</div>',
        '	',
        '	<div class="mpinWhiteGrBtn mpinBtm10" id="mpin_mobile">',
        '		<%=hlp.text("mobile_header_txt1") %>',
        '		<span class="mpinColorRed"><%= hlp.text("mobile_header_donot") %></span>',
        '		<%=hlp.text("mobile_header_txt3") %>',
        '	</div>',
        '	',
        '</div>',
        '',
        '	',
        '',
        '',
        '<div id="mpinFooter">',
        '	<a href="#" class="mpinHelpHub" id="mpin_desktop_hub"></a>',
        '    <div id="homeBtn">',
        '    </div>',
        '</div>'].join('');
})();