(function() {
    mpin.template = {};
    mpin.template['mobile-setup'] = ['<div class="mpinHeader">',
        '    <div class="mpinLogo mpPointer"></div>',
        '	<div class="mpinHome mpPointer" id="mpin_home"></div>',
        '</div>',
        '',
        '<div class="mpinHeaderRow">',
        '	<%=hlp.text( "mobileGet_header") %>',
        '</div>',
        '',
        '<div class="mpinMain">',
        '	<div class="mpinCenter mpinCenter5">',
        '		',
        '		<span id="mpin_qrcode">',
        '		</span>',
        '',
        '		<p class="mpinJustifyTxt">',
        '			<i class="mpinInfo"></i>',
        '			<%=hlp.text( "mobileGet_text1") %>',
        '		</p>',
        '		<span class="mpinPurple mpWrapped">',
        '			<%= mobileAppFullURL %>',
        '		</span>',
        '	</div>',
        '	',
        '		<div class="mpinBtnBox">',
        '',
        '			<div class="mpinButton mpGreen" id="mpinbtn_mobile">',
        '				<span class="iconArrow"></span>',
        '				<%=hlp.text( "mobile_footer_btn")%>',
        '			</div>',
        '		</div>',
        '	',
        '</div>',
        '',
        '',
        '<div class="mpinFooter">',
        '	<div class="mpinPowered"></div>',
        '	<div class="mpinHelpHub mpPointer" id="mpin_helphub"></div>',
        '</div>'].join('');

    mpin.template['landing'] = ['<div class="mpinHeaderBig">',
        '	<div id="mpinLogo"></div>',
        '</div>',
        '',
        '<div class="mpinHeaderRow mpHeaderPadd">',
        '	<div class="mpinBorderBottom">',
        '		<div class="mpinMobileIcon"></div>',
        '	</div>',
        '</div>',
        '',
        '<div class="mpinMain mpNoHeight">',
        '	<div class="mpinBtnBox mpNoPadding">',
        '		',
        '		<!-- BIG BTN -->',
        '		<div class="mpinButton mpGreen mpFontNormal">',
        '			<div class="mpBorderWhite">',
        '				<%=hlp.text( "signin_mobile_btn_text") %>',
        '			</div>',
        '			<div class="mpbtnPadding">',
        '				<%=hlp.text( "mobileAuth_text1") %>',
        '				<div id="mpinAccessNumber"></div>',
        '			</div>',
        '			<i class="mpinInfoCenter" id="mpin_access_help"></i>',
        '			<div class="mpbtnExpire" id="mpin_seconds"></div>',
        '		</div>',
        '		',
        '		<div class="mpinButton mpGreen" id="mpin_action_setup">',
        '			<span class="mpbtnIconArrow"></span>',
        '			<%=hlp.text( "home_button_getMobile") %>',
        '		</div>',
        '		',
        '		',
        '		',
        '		<div class="mpinButton mpBtnOnlyBlue" id="mpin_desktop">',
        '			 <%=hlp.text( "landing_button_newuser") %>',
        '		</div>',
        '	</div>',
        '</div>',
        '',
        '<div class="mpinFooter mpinFooterHome">',
        '	<info class="mpinHelpInfo" id="mpin_help">',
        '		<i></i>',
        '		<%= hlp.text( "home_hlp_link") %>',
        '	</info>',
        '</div>'].join('');

    mpin.template['accounts-panel'] = ['<div class="mpinLists" >',
        '	<ul id="mpin_accounts_list">',
        '		<!-- identities(accounts) list here -->',
        '	</ul>',
        '</div>',
        '',
        '<div class="mpinBtnBox">',
        '	<div class="mpinButton" id="mpin_add_identity">',
        '		<%=hlp.text("account_button_addnew") %>',
        '	</div>',
        '	<div class="mpinButton mpGreen" id="mpin_phone">',
        '		<%=hlp.text("signin_mobile_btn_text") %>',
        '	</div>',
        '</div>'].join('');

    mpin.template['delete-warning'] = ['<div class="mpinHeader">',
        '    <div class="mpinLogo mpPointer"></div>',
        '	<div class="mpinHome mpPointer" id="mpin_home"></div>',
        '</div>',
        '',
        '<div class="mpinHeaderRow">',
        '	<%=hlp.text( "deactivated_header") %>',
        '</div>',
        '',
        '<div class="mpinMain mpPaddTop10">',
        '	<div class="mpinCenter mpinCenter5">',
        '	',
        '		<p class="mpinIdentityText"> <%=  userId %></p>',
        '		',
        '		<%=hlp.text( "deactivated_text1") %>',
        '		<p>',
        '			<%=hlp.text( "deactivated_text2") %>',
        '		</p>',
        '    </div>',
        '	',
        '	<div class="mpinBtnBox">',
        '		<div class="mpinButton" id="mp_action_go">',
        '			<%=hlp.text( "deactivated_button_register") %>',
        '		</div>',
        '	</div>',
        '	',
        '	<info class="mpinHelpInfo" id="mpin_help">',
        '		<i></i>',
        '		<%= hlp.text( "home_hlp_link") %>',
        '	</info>',
        '	',
        '</div>',
        '',
        '<div class="mpinFooter">',
        '	<div class="mpinPowered"></div>',
        '	<div class="mpinHelpHub mpPointer" id="mpin_helphub"></div>',
        '</div>'].join('');

    mpin.template['home_mobile'] = ['<div id="buttonsContainer">',
        '    <div class="mpinBtn mpinGreenBtn" id="mpin_mobile">',
        '        <span class="btnLabel">',
        '			<span class="mpinBold"><%=hlp.text( "signin_btn_mobile1") %></span>',
        '			<%=hlp.text( "signin_btn_mobile2") %>',
        '		</span>',
        '    </div>',
        '</div>',
        '<div class="mpinCenterTxt">',
        '	<%=hlp.text( "home_txt_between_btns") %>',
        '</div>'].join('');

    mpin.template['user-settings'] = ['',
        '<div class="mpinHeaderRow">',
        '	<%=hlp.text( "settings_title") %>',
        '</div>',
        '',
        '<div class="mpinCenter mpinCenter5">',
        '	<p class="mpinIdentityText">',
        '		<%= name %>',
        '	</p>',
        '</div>',
        '',
        '<div class="mpinFooterRow">',
        '',
        '	<div class="mpinBtnBox">',
        '		<div class="mpinButton" id="mpin_deluser_btn">',
        '			<%=hlp.text( "account_button_delete")%>',
        '		</div>',
        '		',
        '		<div class="mpinButton" id="mpin_reactivate_btn">',
        '			<%=hlp.text( "account_button_reactivate")%>',
        '		</div>',
        '		',
        '		<div class="mpinButton mpBtnOnlyGreen" id="mpin_cancel_btn">',
        '			<%=hlp.text( "account_button_backToList")%>',
        '		</div>',
        '	',
        '	</div>',
        '',
        '	',
        '</div>',
        '',
        '<!--',
        '<div id="mp_accountListView" class="active">',
        '    <div class="mp_customScrollBox">',
        '        <div class="mp_container">',
        '            <div id="mp_accountContent" class="mp_content">',
        '			',
        '			',
        '			    <div class="mp_accountField" style="padding: 10px 5px 50px 5px;">',
        '					<%=name %>',
        '				</div>',
        '				<div style="padding:0px 10px">',
        '					<button id="mp_deluser" class="mpinBtn" style="padding: 5px;" tabindex=-1>',
        '						<%=hlp.text( "account_button_delete")%>',
        '					</button>',
        '					<br />',
        '					<button id="mp_reactivate" class="mpinBtn" style="padding: 5px;" tabindex=-1>',
        '						<%=hlp.text( "account_button_reactivate")%>',
        '					</button>',
        '				</div>',
        '			',
        '			',
        '			',
        '			</div>',
        '        </div>',
        '    </div>',
        '</div>',
        '',
        '	',
        '<div id="bottomBtnHolder">',
        '	<button class="mpinBtn" id="mp_acclist_cancel">',
        '		<span class="btnLabel"><%=hlp.text("account_button_backToList") %></span>',
        '	</button>',
        '</div>',
        '-->'].join('');

    mpin.template['blank'] = ['﻿<div class="mpinHeader">',
        '    <div class="mpinLogo mpPointer"></div>',
        '	<div class="mpinHome mpPointer"></div>',
        '</div>',
        '',
        '<div class="mpinIdentityRow">',
        '	<div class="mpinArrowDown mpPointer mpHide" id="show_identity"></div>',
        '	<div class="mpinIdentity mpLeft20">alice@your-domain.com</div>',
        '</div>',
        '',
        '',
        '<div class="mpinMain mpPaddTop10">',
        '	<div class="mpinLists">',
        '		<ul>',
        '			<li class="mpinRow">',
        '				<div class="mpinSettings"></div>',
        '				ONE ONE',
        '			</li>',
        '			<li class="mpinRow">',
        '				<div class="mpinSettings"></div>',
        '				Two Two',
        '			</li>',
        '			<li class="mpinRow">',
        '				<div class="mpinSettings"></div>',
        '				ONE ONE',
        '			</li>',
        '			<li class="mpinRow">',
        '				<div class="mpinSettings"></div>',
        '				ONE ONE',
        '			</li>',
        '			<li class="mpinRow">',
        '				<div class="mpinSettings"></div>',
        '				ONE ONE',
        '			</li>',
        '		</ul>',
        '	</div>',
        '	',
        '	<div class="mpinBtnBox">',
        '		<div class="mpinButton">',
        '			Add a new identity',
        '		</div>',
        '		',
        '		<div class="mpinButton mpGreen">',
        '			Sign in with your Smartphone',
        '		</div>',
        '	</div>',
        '	',
        '</div>',
        '',
        '',
        '<div class="mpinIdentityRow mpinFooterRow">',
        '	<div class="mpinArrowUp mpPointer"></div>',
        '</div>',
        '	',
        '<!--',
        '<div class="mpinMain mpinPinpad">',
        '',
        '	<div class="mpinInput">',
        '		<div class="mpinInputIn">',
        '			<div class="mpinCircle">',
        '				<div class="mpinCircleOut"></div>',
        '				<div class="mpinCircleIn"></div>',
        '			</div>',
        '			',
        '			<div class="mpinCircle">',
        '				<div class="mpinCircleOut"></div>',
        '				<div class="mpinCircleIn"></div>',
        '			</div>',
        '			<div class="mpinCircle">',
        '				<div class="mpinCircleOut"></div>',
        '				<div class="mpinCircleIn"></div>',
        '			</div>',
        '			<div class="mpinCircle">',
        '				<div class="mpinCircleOut"></div>',
        '				<div class="mpinCircleIn"></div>',
        '			</div>',
        '		</div>',
        '    </div>',
        '	',
        '	',
        '	<div class="mpin-pre-row">',
        '        <div class="mpin-row">',
        '            <button class="mpinPadBtn" data-value="1">',
        '                1',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="2">',
        '                2',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="3">',
        '                3',
        '            </button>',
        '        </div>',
        '    </div>',
        '    <div class="mpin-pre-row">',
        '        <div class="mpin-row">',
        '            <button class="mpinPadBtn" data-value="4">',
        '                4',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="5">',
        '                5',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="6">',
        '                6',
        '            </button>',
        '        </div>',
        '    </div>',
        '    <div class="mpin-pre-row">',
        '        <div class="mpin-row">',
        '            <button class="mpinPadBtn" data-value="7">',
        '                7',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="8">',
        '                8',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="9">',
        '                9',
        '            </button>',
        '        </div>',
        '    </div>',
        '    <div class="mpin-pre-row">',
        '        <div class="mpin-row mpin-bottom">',
        '            <button class="mpinPadBtn mpinPadBtnClear" data-value="clear" id="mpinClear">',
        '                clear',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="0">',
        '                0',
        '            </button>',
        '            <button class="mpinPadBtn mpinPadBtnLogin" data-value="go" id="mpinLogin">',
        '                login',
        '            </button>',
        '        </div>',
        '    </div>',
        '',
        '</div>',
        '-->	',
        '',
        '<div class="mpinFooter">',
        '	<div class="mpinPowered"></div>',
        '	<div class="mpinHelpHub mpPointer"></div>',
        '</div>'].join('');

    mpin.template['setup-home-2'] = ['<div class="mpinHeaderRow">',
        '	<%=hlp.text( "setup_header") %>',
        '</div>',
        '',
        '',
        '<div class="mpinMain mpPaddTop10">',
        '	',
        '	<div class="mpinCenter">',
        '		<%=hlp.text( "setup_text1") %>',
        '		<input type="email" id="emailInput" class="mpinInput" placeholder="<%=hlp.text( "setup_placeholder") %>" value="<%= userId %>">',
        '    </div>',
        '	',
        '	<div class="mpinBtnBox">',
        '		<div class="mpinButton" id="mpin_setup">',
        '			<%=hlp.text( "setup_button_setup") %>',
        '		</div>',
        '	</div>',
        '',
        '	',
        '	<info class="mpinHelpInfo mpAbsolute" id="mpin_help">',
        '		<i></i>',
        '		<%= hlp.text( "home_hlp_link") %>',
        '	</info>',
        '	',
        '</div>'].join('');

    mpin.template['setup'] = ['<div class="mpinHeader">',
        '    <div class="mpinLogo mpPointer"></div>',
        '	<div class="mpinHome mpPointer" id="mpin_home"></div>',
        '</div>',
        '',
        '<div class="mpinIdentityRow">',
        '	<div class="mpinArrowDown mpPointer mpHide" id="show_identity"></div>',
        '	<div class="mpinIdentity mpLeft20"><%= email %></div>',
        '</div>',
        '',
        '',
        '<div class="mpinMain mpinPinpad">',
        '	<div class="mpinInput" id="mpin_input_parent">',
        '	',
        '		<div class="mpinInputIn mpHide" id="mpin_input_circle">',
        '			<div class="mpinCircle" id="mpin_circle_1">',
        '				<div class="mpinCircleOut"></div>',
        '			</div>',
        '			',
        '			<div class="mpinCircle" id="mpin_circle_2">',
        '				<div class="mpinCircleOut"></div>',
        '			</div>',
        '			<div class="mpinCircle" id="mpin_circle_3">',
        '				<div class="mpinCircleOut"></div>',
        '			</div>',
        '			<div class="mpinCircle" id="mpin_circle_4">',
        '				<div class="mpinCircleOut"></div>',
        '			</div>',
        '		</div>',
        '		',
        '		<div class="mpinInputIn mpin80width" id="mpin_input_text">',
        '			<i id="mpin_help_pinpad"></i>',
        '				<span class="mpinInputText" id="mpin_inner_text">		',
        '					Initializing...',
        '				</span>',
        '		</div>',
        '		',
        '    </div>',
        '	',
        '	',
        '	<div class="mpin-pre-row">',
        '        <div class="mpin-row">',
        '            <button class="mpinPadBtn" data-value="1">',
        '                1',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="2">',
        '                2',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="3">',
        '                3',
        '            </button>',
        '        </div>',
        '    </div>',
        '    <div class="mpin-pre-row">',
        '        <div class="mpin-row">',
        '            <button class="mpinPadBtn" data-value="4">',
        '                4',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="5">',
        '                5',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="6">',
        '                6',
        '            </button>',
        '        </div>',
        '    </div>',
        '    <div class="mpin-pre-row">',
        '        <div class="mpin-row">',
        '            <button class="mpinPadBtn" data-value="7">',
        '                7',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="8">',
        '                8',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="9">',
        '                9',
        '            </button>',
        '        </div>',
        '    </div>',
        '    <div class="mpin-pre-row">',
        '        <div class="mpin-row mpin-bottom">',
        '            <button class="mpinPadBtn2 mpinBtnDisabled" data-value="clear" id="mpin_clear">',
        '                clear',
        '            </button>',
        '            <button class="mpinPadBtn" data-value="0">',
        '                0',
        '            </button>',
        '            <button class="mpinPadBtn2 mpinBtnDisabled" data-value="go" id="mpin_login">',
        '                setup',
        '            </button>',
        '        </div>',
        '    </div>',
        '',
        '</div>',
        '',
        '',
        '',
        '<div class="mpinFooter">',
        '	<div class="mpinPowered"></div>',
        '	<div class="mpinHelpHub mpPointer" id="mpin_helphub"></div>',
        '</div>'].join('');

    mpin.template['delete-panel'] = ['<div class="mpinHeaderRow">',
        '	<%=hlp.text( "settings_title") %>',
        '</div>',
        '',
        '<div class="mpinMain">',
        '	<!-- <div class="mpinCenter">-->',
        '	<div class="mpinCenter mpinCenter5">',
        '		<%=hlp.text( "account_delete_question") %>',
        '		',
        '		<p class="mpinIdentityText mpPaddTop10">',
        '			<%= name %>',
        '		</p>	',
        '	</div>',
        '	',
        '	<div class="mpinFooterRow">',
        '		<div class="mpinBtnBox">',
        '			<div class="mpinButton" id="mpin_deluser_btn">',
        '				<%=hlp.text( "account_delete_button")%>',
        '			</div>',
        '',
        '			<div class="mpinButton mpBtnOnlyGreen" id="mpin_cancel_btn">',
        '				<%=hlp.text( "account_button_cancel")%>',
        '			</div>',
        '		</div>',
        '	',
        '</div>',
        '</div>',
        '',
        ''].join('');

    mpin.template['setup-done'] = ['',
        '<div class="mpinHeader">',
        '    <div class="mpinLogo mpPointer"></div>',
        '	<div class="mpinHome mpPointer" id="mpin_home"></div>',
        '</div>',
        '',
        '<div class="mpinHeaderRow">',
        '	<%=hlp.text( "setupDone_header") %>',
        '</div>',
        '',
        '<div class="mpinMain mpPaddTop10">',
        '	',
        '	<div class="mpinCenter mpinCenter5">',
        '		<%=hlp.text( "setupDone_text1") %>',
        '		',
        '		<p class="mpinIdentityText">',
        '			<%= userId %>',
        '		</p>',
        '		',
        '			<%=hlp.text( "setupDone_text2") %>',
        '		<p>',
        '			<%=hlp.text( "setupDone_text3") %>',
        '		</p>',
        '    </div>',
        '',
        '	<div class="mpinBtnBox">',
        '		<div class="mpinButton" id="mpin_login_now">',
        '			<%=hlp.text( "setupDone_button_go") %>',
        '		</div>',
        '	</div>',
        '',
        '</div>',
        '',
        '<div class="mpinFooter">',
        '	<div class="mpinPowered"></div>',
        '	<div class="mpinHelpHub mpPointer" id="mpin_helphub"></div>',
        '</div>'].join('');

    mpin.template['help-hub-3'] = ['﻿<div class="mpinHeader">',
        '    <div class="mpinLogo mpPointer"></div>',
        '	<div class="mpinHome mpPointer" id="mpin_home"></div>',
        '</div>',
        '',
        '<info class="mpinHelpInfo helpHubTitle">',
        '	<%= hlp.text( "help_hub_li1") %>',
        '</info>',
        '',
        '<!-- <div class="mpinMain mpPaddTop10"> -->',
        '<div class="mpinMain">',
        '	<div class="mpinHelpBlock">',
        '		<p><%= hlp.text( "help_hub_3_p1") %></p>',
        '		<p><%= hlp.text( "help_hub_3_p2") %></p>',
        '	</div>',
        '	',
        '	<div class="mpinBtnBox">',
        '		<div class="mpinButton" id="mpin_help_hub">',
        '			<%=hlp.text( "help_hub_return_button")%>',
        '		</div>',
        '	</div>',
        '</div>',
        '',
        '',
        '<div class="mpinFooter">',
        '	<div class="mpinPowered"></div>',
        '	<div class="mpinHelpHub mpPointer" id="mpin_helphub"></div>',
        '</div>',
        '',
        ''].join('');

    mpin.template['help-hub'] = ['<div class="mpinHeader">',
        '    <div class="mpinLogo mpPointer"></div>',
        '	<div class="mpinHome mpPointer" id="mpin_home"></div>',
        '</div>',
        '<!-- for all subViews-->',
        '',
        '<info class="mpinHelpInfo helpHubTitle">',
        '	<i></i>',
        '	<%= hlp.text( "help_hub_title") %>',
        '</info>',
        '',
        '<!-- <div class="mpinMain mpPaddTop10"> -->',
        '<div class="mpinMain">',
        '',
        '	<div class="mpinHelpBlock">',
        '		<ul>',
        '			<li id="mpin_hub_li1"><%= hlp.text( "help_hub_li1") %></li>',
        '			<li id="mpin_hub_li2"><%= hlp.text( "help_hub_li2") %></li>',
        '			<li id="mpin_hub_li3"><%= hlp.text( "help_hub_li3") %></li>',
        '			<li id="mpin_hub_li4"><%= hlp.text( "help_hub_li4") %></li>',
        '			',
        '		</ul>',
        '	</div>',
        '',
        '	<div class="mpinBtnBox">',
        '		<div class="mpinButton" id="mpin_close_hub">',
        '			<%=hlp.text( "help_hub_button")%>',
        '		</div>',
        '	</div>',
        '</div>',
        '',
        '',
        '<div class="mpinFooter">',
        '	<div class="mpinPowered"></div>',
        '	<div class="mpinHelpHub mpPointer" id="mpin_helphub"></div>',
        '</div>'].join('');

    mpin.template['reactivate-panel'] = ['<div class="mpinHeaderRow">',
        '	<%=hlp.text( "settings_title") %>',
        '</div>',
        '',
        '<div class="mpinMain">',
        '	<div class="mpinCenter mpinCenter5">',
        '		<%=hlp.text( "account_reactivate_question") %>',
        '		',
        '		<p class="mpinIdentityText mpPaddTop10">',
        '			<%= name %>',
        '		</p>	',
        '	</div>',
        '		',
        '',
        '	',
        '</div>',
        '',
        '	<div class="mpinFooterRow">',
        '',
        '		<div class="mpinBtnBox">',
        '			<div class="mpinButton" id="mpin_reactivate_btn">',
        '				<%=hlp.text( "account_reactivate_button")%>',
        '			</div>',
        '',
        '			<div class="mpinButton mpBtnOnlyGreen" id="mpin_cancel_btn">',
        '				<%=hlp.text( "account_button_cancel")%>',
        '			</div>',
        '		</div>',
        '		',
        '	</div>'].join('');

    mpin.template['home'] = ['<div class="mpinHeaderBig">',
        '	<div id="mpinLogo"></div>',
        '</div>',
        '',
        '<div class="mpinHeaderBig">',
        '	<%=hlp.text( "home_intro_text") %>',
        '</div>',
        '',
        '<div class="mpinMain mpPaddTop10"> ',
        '	<div class="mpinBtnBox">',
        '	',
        '		<div class="mpinButton mpGreen mpBtnHome" id="mpin_mobile">',
        '			<%=hlp.text( "signin_mobile_btn_text") %>',
        '			<p>',
        '				<%=hlp.text( "signin_btn_mobile2")%>',
        '			</p>',
        '			',
        '		</div>',
        '		',
        '		<div class="mpinCenter mpinCenter5 mpHomeTxt">',
        '			<%=hlp.text( "home_txt_between_btns") %>',
        '		</div>',
        '		',
        '',
        '		<div class="mpinButton mpBtnHome" id="mpin_desktop">',
        '			<%=hlp.text( "signin_btn_desktop1") %>',
        '			<p>',
        '			<%=hlp.text( "signin_btn_desktop2")%>',
        '			</p>',
        '		</div>',
        '	</div>',
        '</div>',
        '',
        '<div class="mpinFooter mpinFooterHome">',
        '	<info class="mpinHelpInfo" id="mpin_help">',
        '		<i></i>',
        '		<%= hlp.text( "home_hlp_link") %>',
        '	</info>',
        '</div>',
        ''].join('');

    mpin.template['mpin'] = ['﻿	<div class="mpinContainer">',
        '		<div id="mpinHolder">',
        '			<div id="mpinMiracle" class="mpinMaster">',
        '				',
        '			</div>',
        '		</div>',
        '	</div>'].join('');

    mpin.template['help-hub-1'] = ['﻿<div class="mpinHeader">',
        '    <div class="mpinLogo mpPointer"></div>',
        '	<div class="mpinHome mpPointer" id="mpin_home"></div>',
        '</div>',
        '',
        '<info class="mpinHelpInfo helpHubTitle">',
        '	<%= hlp.text( "help_hub_li1") %>',
        '</info>',
        '',
        '<!-- <div class="mpinMain mpPaddTop10"> -->',
        '<div class="mpinMain">',
        '	<div class="mpinHelpBlock">',
        '		<p><%= hlp.text( "help_hub_3_p1") %></p>',
        '		<p><%= hlp.text( "help_hub_3_p2") %></p>',
        '	</div>',
        '	',
        '	<div class="mpinBtnBox">',
        '		<div class="mpinButton" id="mpin_help_hub">',
        '			<%=hlp.text( "help_hub_return_button")%>',
        '		</div>',
        '	</div>',
        '</div>',
        '',
        '',
        '<div class="mpinFooter">',
        '	<div class="mpinPowered"></div>',
        '	<div class="mpinHelpHub mpPointer" id="mpin_helphub"></div>',
        '</div>',
        '',
        ''].join('');

    mpin.template['identity-not-active'] = ['<div class="mpinHeader">',
        '    <div class="mpinLogo mpPointer"></div>',
        '	<div class="mpinHome mpPointer" id="mpin_home"></div>',
        '</div>',
        '',
        '<div class="mpinHeaderRow">',
        '	<%=hlp.text( "setupNotReady_header") %>',
        '</div>',
        '',
        '<div class="mpinMain mpPaddTop10">',
        '	<div class="mpinCenter mpinCenter5">',
        '		<%=hlp.text( "setupNotReady_text1") %>',
        '		<p class="mpinIdentityText">',
        '			<%= email %>',
        '		</p>		',
        '		<%=hlp.text( "setupNotReady_text2") %>',
        '		<p>',
        '			<%=hlp.text( "setupNotReady_text3") %>',
        '		</p>',
        '    </div>',
        '	',
        '	<!-- <div class="mpinFooterRow"> -->',
        '		<div class="mpinBtnBox">',
        '			<div class="mpinButton" id="mpin_activate_btn">',
        '				<%=hlp.text( "setupNotReady_button_check")%>',
        '			</div>',
        '			',
        '			<div class="mpinButton" id="mpin_resend_btn">',
        '				<%=hlp.text( "setupNotReady_button_resend")%>',
        '			</div>',
        '',
        '			<div class="mpinButton mpBtnOnlyGreen" id="mpin_accounts_btn">',
        '				<%=hlp.text( "setupNotReady_button_back")%>',
        '			</div>',
        '		</div>',
        '	<!-- </div> -->',
        '</div>',
        '',
        '<div class="mpinFooter">',
        '	<div class="mpinPowered"></div>',
        '	<div class="mpinHelpHub mpPointer" id="mpin_helphub"></div>',
        '</div>'].join('');

    mpin.template['login'] = ['<div class="mpinHeader">',
        '    <div class="mpinLogo mpPointer"></div>',
        '	<div class="mpinHome mpPointer" id="mpin_home"></div>',
        '</div>',
        '',
        '<div class="mpinMain mpinPinpad mpinAnimateIn" id="mpin_pinpad">',
        '',
        '    <div class="mpinIdentityRow">',
        '        <div class="mpinIdentity mpLeft20" id="mpinUser">',
        '            <!-- Place the identities inside -->',
        '',
        '            <p id="mpinCurrentIden"> </p>',
        '',
        '            <div class="mpinArrowDown mpPointer" id="mpin_arrow">',
        '				<img src="<%= hlp.img("arrow-down-black.svg") %>">',
        '			</div>',
        '',
        '            <div id="mpin_identities" class="mpinMain mpinAnimateIn  mpZero">',
        '',
        '            </div>',
        '',
        '        </div>',
        '',
        '    </div>',
        '',
        '    <!-- Div pinpad holder -->',
        '',
        '    <div id="pinpadEls">',
        '            <div class="mpinInput" id="mpin_input_parent">',
        '            ',
        '                <div class="mpinInputIn mpHide" id="mpin_input_circle">',
        '                    <div class="mpinCircle" id="mpin_circle_1">',
        '                        <div class="mpinCircleOut"></div>',
        '                    </div>',
        '                    ',
        '                    <div class="mpinCircle" id="mpin_circle_2">',
        '                        <div class="mpinCircleOut"></div>',
        '                    </div>',
        '                    <div class="mpinCircle" id="mpin_circle_3">',
        '                        <div class="mpinCircleOut"></div>',
        '                    </div>',
        '                    <div class="mpinCircle" id="mpin_circle_4">',
        '                        <div class="mpinCircleOut"></div>',
        '                    </div>',
        '                </div>',
        '                ',
        '                <div class="mpinInputIn mpin70width" id="mpin_input_text">',
        '                    <i id="mpin_help_pinpad"></i>',
        '                        <span class="mpinInputText mpinInputTop" id="mpin_inner_text">      ',
        '                            Initializing...',
        '                        </span>',
        '                </div>',
        '                ',
        '            </div>',
        '            ',
        '            ',
        '            <div class="mpin-pre-row">',
        '                <div class="mpin-row">',
        '                    <button class="mpinPadBtn" data-value="1">',
        '                        1',
        '                    </button>',
        '                    <button class="mpinPadBtn" data-value="2">',
        '                        2',
        '                    </button>',
        '                    <button class="mpinPadBtn" data-value="3">',
        '                        3',
        '                    </button>',
        '                </div>',
        '            </div>',
        '            <div class="mpin-pre-row">',
        '                <div class="mpin-row">',
        '                    <button class="mpinPadBtn" data-value="4">',
        '                        4',
        '                    </button>',
        '                    <button class="mpinPadBtn" data-value="5">',
        '                        5',
        '                    </button>',
        '                    <button class="mpinPadBtn" data-value="6">',
        '                        6',
        '                    </button>',
        '                </div>',
        '            </div>',
        '            <div class="mpin-pre-row">',
        '                <div class="mpin-row">',
        '                    <button class="mpinPadBtn" data-value="7">',
        '                        7',
        '                    </button>',
        '                    <button class="mpinPadBtn" data-value="8">',
        '                        8',
        '                    </button>',
        '                    <button class="mpinPadBtn" data-value="9">',
        '                        9',
        '                    </button>',
        '                </div>',
        '            </div>',
        '            <div class="mpin-pre-row">',
        '                <div class="mpin-row mpin-bottom">',
        '                    <button class="mpinPadBtn2 mpinBtnDisabled" data-value="clear" id="mpin_clear">',
        '                        clear',
        '                    </button>',
        '                    <button class="mpinPadBtn" data-value="0">',
        '                        0',
        '                    </button>',
        '                    <button class="mpinPadBtn2 mpinBtnDisabled" data-value="go" id="mpin_login">',
        '                        login',
        '                    </button>',
        '                </div>',
        '            </div>',
        '    </div>',
        '',
        '	',
        '',
        '</div>',
        '',
        '',
        '',
        '<div class="mpinFooter">',
        '	<div class="mpinPowered"></div>',
        '	<div class="mpinHelpHub mpPointer" id="mpin_helphub"></div>',
        '</div>'].join('');

    mpin.template['setup-home'] = ['<div class="mpinHeader">',
        '    <div class="mpinLogo mpPointer"></div>',
        '	<div class="mpinHome mpPointer" id="mpin_home"></div>',
        '</div>',
        '',
        '',
        '<div class="mpinHeaderRow">',
        '	<%=hlp.text( "setup_header") %>',
        '</div>',
        '',
        '',
        '<div class="mpinMain mpPaddTop10">',
        '	',
        '	<div class="mpinCenter">',
        '		<%=hlp.text( "setup_text1") %>',
        '		<input type="email" id="emailInput" class="mpinInput" placeholder="<%=hlp.text( "setup_placeholder") %>" value="<%= userId %>">',
        '    </div>',
        '	',
        '	<div class="mpinBtnBox">',
        '		<div class="mpinButton" id="mpin_setup">',
        '			<%=hlp.text( "setup_button_setup") %>',
        '		</div>',
        '	</div>',
        '',
        '	',
        '	<info class="mpinHelpInfo mpAbsolute" id="mpin_help">',
        '		<i></i>',
        '		<%= hlp.text( "home_hlp_link") %>',
        '	</info>',
        '	',
        '</div>',
        '',
        '<div class="mpinIdentityRow mpinFooterRow mpHide" id="mpin_accounts_list">',
        '	<div class="mpinArrowDown mpPointer close mpinAUp" id="mpin_arrow">',
        '		<img src="<%= hlp.img("arrow-down-black.svg") %>">',
        '		',
        '	</div>',
        '</div>',
        '',
        '',
        '<div class="mpinFooter">',
        '	<div class="mpinPowered"></div>',
        '	<div class="mpinHelpHub mpPointer" id="mpin_helphub"></div>',
        '</div>'].join('');

    mpin.template['user-row'] = ['<div class="mpinSettings" id="mpin_settings_<%= iNumber %>"></div>',
        '<a href="" class="mpinSettingsRow" title="<%= name %>" alt="<%= name %>"><%= name %></p>',
        '',
        '<!-- <p class="mpinSettingsRow"><%= name %></p> -->'].join('');

    mpin.template['help-hub-4'] = ['﻿<div class="mpinHeader">',
        '    <div class="mpinLogo mpPointer"></div>',
        '	<div class="mpinHome mpPointer" id="mpin_home"></div>',
        '</div>',
        '',
        '<info class="mpinHelpInfo helpHubTitle">',
        '	<%= hlp.text( "help_hub_li1") %>',
        '</info>',
        '',
        '<!-- <div class="mpinMain mpPaddTop10"> -->',
        '<div class="mpinMain">',
        '	<div class="mpinHelpBlock">',
        '		<p><%= hlp.text( "help_hub_3_p1") %></p>',
        '		<p><%= hlp.text( "help_hub_3_p2") %></p>',
        '	</div>',
        '	',
        '	<div class="mpinBtnBox">',
        '		<div class="mpinButton" id="mpin_help_hub">',
        '			<%=hlp.text( "help_hub_return_button")%>',
        '		</div>',
        '	</div>',
        '</div>',
        '',
        '',
        '<div class="mpinFooter">',
        '	<div class="mpinPowered"></div>',
        '	<div class="mpinHelpHub mpPointer" id="mpin_helphub"></div>',
        '</div>',
        '',
        ''].join('');

    mpin.template['help-tooltip'] = ['﻿<help id="mpinHelpTag">',
        '	<div id="mpinHelpContainer">',
        '	</div>',
        '</help>'].join('');

    mpin.template['help-hub-2'] = ['﻿<div class="mpinHeader">',
        '    <div class="mpinLogo mpPointer"></div>',
        '	<div class="mpinHome mpPointer" id="mpin_home"></div>',
        '</div>',
        '',
        '<info class="mpinHelpInfo helpHubTitle">',
        '	<%= hlp.text( "help_hub_li1") %>',
        '</info>',
        '',
        '<!-- <div class="mpinMain mpPaddTop10"> -->',
        '<div class="mpinMain">',
        '	<div class="mpinHelpBlock">',
        '		<p><%= hlp.text( "help_hub_3_p1") %></p>',
        '		<p><%= hlp.text( "help_hub_3_p2") %></p>',
        '	</div>',
        '	',
        '	<div class="mpinBtnBox">',
        '		<div class="mpinButton" id="mpin_help_hub">',
        '			<%=hlp.text( "help_hub_return_button")%>',
        '		</div>',
        '	</div>',
        '</div>',
        '',
        '',
        '<div class="mpinFooter">',
        '	<div class="mpinPowered"></div>',
        '	<div class="mpinHelpHub mpPointer" id="mpin_helphub"></div>',
        '</div>',
        '',
        ''].join('');

    mpin.template['help-tooltip-home'] = ['<p class="mpinHelpText">',
        '	<%=hlp.text( "help_text_1") %>',
        '</p>',
        '',
        '<div id="buttonsContainer">',
        '    <div class="mpinBtn mpinGreen mpinBtm10" id="mpin_help_ok">',
        '        <span class="btnLabel"><%=hlp.text( "help_ok_btn") %></span>',
        '    </div>',
        '    <div class="mpinBtn mpinGrey mpinBtm10" id="mpin_help_more">',
        '        <span class="btnLabel"><%=hlp.text( "help_more_btn") %></span>',
        '    </div>',
        '</div>'].join('');

    mpin.template['activate-identity'] = ['<div class="mpinHeader">',
        '    <div class="mpinLogo mpPointer"></div>',
        '	<div class="mpinHome mpPointer" id="mpin_home"></div>',
        '</div>',
        '',
        '<div class="mpinHeaderRow">',
        '	<%=hlp.text( "activate_header") %>',
        '</div>',
        '',
        '<div class="mpinMain mpPaddTop10">',
        '	<div class="mpinCenter mpinCenter5">',
        '		<%=hlp.text( "activate_text1") %>',
        '		',
        '		<p class="mpinIdentityText"><%= email %></p>',
        '		',
        '		<%=hlp.text( "activate_text2") %>',
        '		<p>',
        '			<%=hlp.text( "activate_text3") %>',
        '		</p>',
        '    </div>',
        '	',
        '	<div class="mpinBtnBox">',
        '		<div class="mpinButton" id="mpin_activate">',
        '			<%=hlp.text( "activate_btn1") %>',
        '		</div>',
        '		<div class="mpinButton" id="mpin_resend">',
        '			<%=hlp.text( "activate_btn2") %>',
        '		</div>',
        '	</div>',
        '		',
        '</div>',
        '',
        '',
        '<div class="mpinFooter">',
        '	<div class="mpinPowered"></div>',
        '	<div class="mpinHelpHub mpPointer" id="mpin_helphub"></div>',
        '</div>'].join('');

    mpin.template['mobile-login'] = ['<!-- Home/Top Nav Bar -->',
        '<div class="mpinHeader">',
        '    <div class="mpinLogo mpPointer"></div>',
        '	<div class="mpinHome mpPointer" id="mpin_home"></div>',
        '</div>',
        '',
        '<div class="mpinTabMiddle clrGreen mpinBtm10">',
        '<!--',
        '	<div>',
        '		<%=hlp.text("mobile_header_txt1") %>',
        '		<span class="mpinColorRed"><%= hlp.text("mobile_header_donot") %></span>',
        '		<%=hlp.text("mobile_header_txt3") %>',
        '	</div>',
        '-->',
        '	<div>',
        '		<div id="homeIcon">',
        '			<div id="mobileIcon"></div>',
        '		</div>',
        '	</div>',
        '</div>',
        '',
        '<div class="mpinMobileGrBtn mpinBtm10">',
        '	<div class="mpinGrTxt" id="mpinDownWhite">',
        '		Sign in with Smartphone',
        '	</div>',
        '	<div class="mpinGrTxt">',
        '		Your Access Number is:',
        '		',
        '		<span id="mpinAccessNumber">',
        '		</span>',
        '',
        '	</div>',
        '	',
        '	<div class="mpinMobileWhBtn" id="mpin_seconds">',
        '		99 seconds',
        '	</div>',
        '</div>',
        '',
        '<div class="mpinBtn mpinBtm10" id="mpin_action_setup">',
        '    <span class="iconArrow"></span>',
        '    <span class="btnLabel btnLabelArrow">',
        '		<%=hlp.text( "home_button_getMobile") %>',
        '	</span>',
        '</div>',
        '',
        '<div class="mpinMobileGrBtn mpinBtm10" id="mpin_login_desktop">',
        '    <%=hlp.text( "landing_button_newuser") %>',
        '	<!--',
        '		I <span class="mpinColorRed">DO</span> trust this computer',
        '	-->',
        '</div>',
        '',
        '	<info class="mpinHelpInfo" id="mpin_help">',
        '		<i></i>',
        '		<%= hlp.text( "home_hlp_link") %>',
        '	</info>',
        '',
        '',
        '<div id="mpinFooter">',
        '	<a href="#" class="mpinHelpHub" id="mpin_desktop_hub"></a>',
        '    <div id="homeBtn">',
        '    </div>',
        '</div>'].join('');

    mpin.template['mobile'] = ['<div class="mpinHeaderBig">',
        '	<div id="mpinLogo"></div>',
        '</div>',
        '',
        '<div class="mpinHeaderRow mpHeaderPadd mpHeaderTable">',
        '	<div class="mpinTextGreenBorder">',
        '		<div class="mpinGreenText">',
        '			<%=hlp.text("mobile_header_txt1") %>',
        '			<span class="mpinColorRed">',
        '				<%= hlp.text("mobile_header_donot") %>',
        '			</span>',
        '			<%=hlp.text("mobile_header_txt3") %>',
        '		</div>',
        '		<div class="mpinMobileIcon">',
        '		',
        '		</div>',
        '	</div>',
        '</div>',
        '',
        '<div class="mpinMain mpNoHeight">',
        '	<div class="mpinBtnBox mpNoPadding">',
        '		',
        '		<!-- BIG BTN -->',
        '		<div class="mpinButton mpGreen mpFontNormal">',
        '			<div class="mpBorderWhite">',
        '				<%=hlp.text( "signin_mobile_btn_text") %>',
        '			</div>',
        '			<div class="mpbtnPadding">',
        '				<%=hlp.text( "mobileAuth_text1") %>',
        '				<div id="mpinAccessNumber"></div>',
        '			</div>',
        '			<i class="mpinInfoCenter" id="mpin_access_help"></i>',
        '			<div class="mpbtnExpire" id="mpin_seconds"></div>',
        '		</div>',
        '		',
        '		<div class="mpinButton mpGreen" id="mpin_action_setup">',
        '			<span class="mpbtnIconArrow"></span>',
        '			<%=hlp.text( "home_button_getMobile") %>',
        '		</div>',
        '		',
        '		',
        '		',
        '		<div class="mpinButton mpBtnOnlyBlue" id="mpin_desktop">',
        '			I <span class="mpinColorRed">DO</span> trust this computer',
        '		</div>',
        '	</div>',
        '</div>',
        '',
        '',
        '',
        '',
        '<!--',
        '<div class="mpinMobileGrBtn mpinBtm10">',
        '	<div class="mpinGrTxt" id="mpinDownWhite">',
        '		<%=hlp.text( "signin_mobile_btn_text") %>',
        '	</div>',
        '	<div class="mpinGrTxt">',
        '		<%=hlp.text( "mobileAuth_text1") %>',
        '		<span id="mpinAccessNumber">',
        '		</span>',
        '',
        '	</div>',
        '	',
        '	<i class="mpinInfoCenter" id="mpin_access_help"></i>',
        '	<div class="mpinMobileWhBtn" id="mpin_seconds">',
        '		99 seconds',
        '	</div>',
        '</div>',
        '',
        '<div class="mpinBtn mpinBtm10" id="mpin_action_setup">',
        '    <span class="iconArrow"></span>',
        '    <span class="btnLabel btnLabelArrow">',
        '		<%=hlp.text( "home_button_getMobile") %>',
        '	</span>',
        '</div>',
        '',
        '',
        '<div class="mpinMain mpNoHeight">',
        '	<div class="mpinBtnBox mpNoPadding">',
        '		<div class="mpinButton mpBtnOnlyBlue" id="mpin_desktop">',
        '			I <span class="mpinColorRed">DO</span> trust this computer',
        '		</div>',
        '	</div>',
        '</div>',
        '-->',
        '',
        '',
        '<div class="mpinFooter mpinFooterHome">',
        '	<info class="mpinHelpInfo" id="mpin_help">',
        '		<i></i>',
        '		<%= hlp.text( "home_hlp_link") %>',
        '	</info>',
        '</div>',
        ''].join('');

    mpin.template['logout'] = ['<!-- Home/Top Nav Bar -->',
        '',
        '<div id="topNav">',
        '    <div id="mp_action_home">',
        '    </div>',
        '    <div id="mpinLogo">',
        '    </div>',
        '</div>',
        '',
        '<!-- User section -->',
        '',
        '<div id="header">',
        '  <div id="menuIcon"></div>',
        '  <div id="mpinLogo"></div>',
        '</div>',
        '',
        '<!-- Input button -->',
        '',
        '<div id="identityContainer">',
        '',
        '  <div class="identityMainText">',
        '      <div class="congrats">',
        '        <%= hlp.text("logout_text1") %>',
        '      </div>',
        ' ',
        '  </div>',
        '',
        '  <div id="buttonsContainer">',
        '      <div class="mpinBtn" id="mpin_action_logout">',
        '          <span class="iconArrow"></span>',
        '          <span class="btnLabel"><%= hlp.text("logout_button") %></span>',
        '      </div>',
        '  </div> ',
        '',
        '</div>',
        '',
        '<div id="mpinFooter">',
        '    <div id="homeBtn">',
        '    </div>',
        '</div>'].join('');

    mpin.template['desktop'] = ['﻿<!-- Home/Top Nav Bar -->',
        '<div id="header">',
        '    <div id="mpinLogo"></div>',
        '</div> ',
        '',
        '<div class="mpinTabMiddle clrBlue mpinBtm10">',
        '	<div>',
        '		<%=hlp.text("mobile_header_txt1") %>',
        '		<span class="mpinColorRed"><%= hlp.text("mobile_header_do") %></span>',
        '		<%=hlp.text("mobile_header_txt3") %>',
        '	</div>',
        '	<div>',
        '		<div id="homeIcon">',
        '			<div id="desktopIcon"></div>',
        '		</div>',
        '	</div>',
        '</div>',
        '',
        '<div id="buttonsContainer">',
        '	<div class="mpinBtn mpinBtm10">',
        '		<span class="iconArrow"></span>',
        '		<span class="btnLabel btnLabelArrow"><%=hlp.text( "signin_btn_desktop1") %></span>',
        '	</div>',
        '',
        '	<div class="mpinBtn mpinBtm10">',
        '		<span class="iconArrow"></span>',
        '		<span class="btnLabel btnLabelArrow"><%=hlp.text( "signin_btn_desktop2") %></span>',
        '	</div>',
        '	',
        '	<div class="mpinWhiteGrBtn mpinBtm10" id="mpin_mobile">',
        '		<%=hlp.text("mobile_header_txt1") %>',
        '		<span class="mpinColorRed"><%= hlp.text("mobile_header_donot") %></span>',
        '		<%=hlp.text("mobile_header_txt3") %>',
        '	</div>',
        '	',
        '</div>',
        '',
        '	',
        '',
        '',
        '<div id="mpinFooter">',
        '	<a href="#" class="mpinHelpHub" id="mpin_desktop_hub"></a>',
        '    <div id="homeBtn">',
        '    </div>',
        '</div>'].join('');
})();